# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Test CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
    
    - name: Maven verify loginservice
      run: mvn verify --file LoginRestService/pom.xml
    
    - name: Maven verify logicservice
      run: mvn verify --file MastermindLogic/pom.xml
