# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI AutoTest FrontEnd

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci --prefix mastermindview/
    - run: npm run build --prefix mastermindview/ --if-present
    - run: npm run lint --prefix mastermindview/
    - run: npm test --prefix mastermindview/
